spring:
  datasource:
    druid:
      master:
        url: jdbc:mysql://12.18.1.7:3306/zhgd?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
        username: root
        password: djbcdjbcucds
  redis:
    host: 12.18.1.79
    port: 6379
    password: hn
logging:
  level:
    com.ruoyi: info
    org.springframework: info
    com.hikvision: info
ruoyi:
  profile: ruoyi/uploadPath/wangjun
gbs:
  host: 13.7.10.17:4
